# Generated by Django 4.2.8 on 2023-12-08 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoAgenda',
            new_name='HistoricoAgendamento',
        ),
    ]
