# Generated by Django 4.2.8 on 2024-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemservico',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
