# Generated by Django 4.2.8 on 2024-01-10 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
