# Generated by Django 4.2.8 on 2023-12-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_historicoagenda_historicoagendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoagendamento',
            name='data_agendamento',
            field=models.DateTimeField(),
        ),
    ]
