# Generated by Django 4.2.8 on 2023-12-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_historicoagendamento_data_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='status',
            new_name='status_agendamento',
        ),
    ]
