# Generated by Django 4.2.8 on 2024-01-19 17:39

import datetime
from django.db import migrations, models
from datetime import date 


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 1, 19)),
        ),
    ]
