# Generated by Django 4.2.8 on 2024-01-18 06:27
from datetime import date
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 1, 18)),
        ),
    ]
