# Generated by Django 4.2.8 on 2024-01-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status_verificacao',
            field=models.CharField(choices=[('N', 'Nao_Verificado'), ('V', 'Verificado')], default='N', max_length=2),
        ),
    ]
