# Generated by Django 4.2.8 on 2024-01-20 04:15

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_agendamento_status_verificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='status_verificacao',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 1, 20)),
        ),
    ]
