# Generated by Django 4.2.8 on 2024-02-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_agendamento_preco_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidelidade',
            name='desconto',
            field=models.IntegerField(default=0, verbose_name='Desconto em porcentagem'),
        ),
    ]
