# Generated by Django 4.2.8 on 2024-01-22 14:18

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_remove_agendamento_status_verificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 1, 22)),
        ),
    ]
