# Generated by Django 4.2.8 on 2024-02-02 22:15

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_agendamento_quantidade_concluido_fidelidade_cupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=datetime(2024, 2, 2)),
        ),
    ]
