# Generated by Django 4.2.8 on 2024-02-04 11:15

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_remove_agendamento_quantidade_concluido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fidelidade',
            name='cupon',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 2, 4)),
        ),
    ]
