# Generated by Django 4.2.8 on 2024-02-06 15:43

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_remove_fidelidade_cupon_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='preco_servico',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Preço do Serviço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 2, 6)),
        ),
    ]
