# Generated by Django 4.2.8 on 2024-02-15 02:11

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_agendamento_preco_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fidelidade',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='fidelidade',
            name='status',
        ),
        migrations.AddField(
            model_name='fidelidade',
            name='desconto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fidelidade',
            name='descricao',
            field=models.CharField(default=1, max_length=350, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fidelidade',
            name='nome',
            field=models.CharField(default=2, max_length=50, verbose_name='Nome da Fidelidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fidelidade',
            name='requisito',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 2, 14)),
        ),
    ]
