# Generated by Django 4.2.8 on 2024-02-16 02:12

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_remove_fidelidade_agenda_remove_fidelidade_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 2, 15)),
        ),
    ]
