# Generated by Django 4.2.8 on 2024-02-23 18:08

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 2, 23)),
        ),
    ]
