# Generated by Django 4.2.8 on 2024-03-01 18:34

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=date(2024, 3, 1)),
        ),
    ]
