# Generated by Django 4.2.8 on 2023-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='horario_fim',
            field=models.TimeField(default=1702584913.5690365),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='horario_inicio',
            field=models.TimeField(default=1702584913.5690365),
        ),
    ]
