# Generated by Django 4.2.8 on 2024-01-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='criado_por',
        ),
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
    ]
