# Generated by Django 4.2.8 on 2024-01-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('agenda', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Users',
        ),
    ]
