# Generated by Django 4.2.8 on 2024-02-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_fidelidade_agenda_remove_fidelidade_status_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='agendamentos_concluidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cupon',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fidelidade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.fidelidade'),
        ),
    ]
