# Generated by Django 4.2.8 on 2024-02-28 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_fidelidade_desconto'),
        ('accounts', '0002_remove_usuario_agendamentos_concluidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fidelidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.fidelidade'),
        ),
    ]
