# Generated by Django 4.2.8 on 2023-12-14 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_disponibilidade_horario_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='horario_fim',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='horario_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
