# Generated by Django 4.2.8 on 2024-01-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('CLiente', 'Cliente'), ('Profissional', 'Profissional')], max_length=50),
        ),
    ]
