# Generated by Django 4.2.8 on 2024-01-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_imagem'),
        ('accounts', '0004_rename_user_usuario'),
    ]

    operations = [
    ]
