# Generated by Django 4.2.8 on 2024-01-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
    ]
