# Generated by Django 4.2.8 on 2024-02-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usuario_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='agendamentos_concluidos',
            field=models.IntegerField(default=0),
        ),
    ]
