# Generated by Django 4.2.8 on 2024-01-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_imagem'),
        ('accounts', '0006_remove_usuario_cargo'),
    ]

    operations = [
    ]
