# Generated by Django 4.2.8 on 2024-02-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usuario_agendamentos_concluidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cupon',
            field=models.IntegerField(default=0),
        ),
    ]
