# Generated by Django 4.2.8 on 2024-02-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usuario_fidelidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fidelidade',
        ),
    ]
