# Generated by Django 4.2.8 on 2024-02-15 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_remove_fidelidade_agenda_remove_fidelidade_status_and_more'),
        ('accounts', '0014_alter_usuario_fidelidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fidelidade',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agenda.fidelidade'),
        ),
    ]
