# Generated by Django 4.2.8 on 2024-02-16 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_agendamento_criado_em'),
        ('accounts', '0016_alter_usuario_fidelidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fidelidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.fidelidade'),
        ),
    ]
