# Generated by Django 4.2.8 on 2024-02-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_usuario_fidelidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='agendamentos_concluidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cupon',
        ),
    ]
