# Generated by Django 4.2.8 on 2024-03-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_alter_agendamento_criado_em'),
        ('accounts', '0018_remove_usuario_agendamentos_concluidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fidelidade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.fidelidade'),
        ),
        migrations.CreateModel(
            name='ImagemUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m/%d/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
