# Generated by Django 4.2.8 on 2024-02-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='criado_em',
        ),
    ]
