# Generated by Django 4.2.8 on 2024-01-10 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='criado_em',
            field=models.DateField(default=datetime.date(2024, 1, 10)),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='valor',
            field=models.CharField(choices=[('1', '10.00'), ('2', '15.00'), ('3', '20.00'), ('4', '30.00')], max_length=20),
        ),
    ]
