# Generated by Django 4.2.8 on 2024-01-19 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_alter_parametro_criado_em_alter_parametro_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='criado_em',
            field=models.DateField(default=datetime.date(2024, 1, 19)),
        ),
    ]
