# Generated by Django 4.2.8 on 2024-02-23 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_remove_parametro_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='criado_em',
            field=models.DateField(default=datetime.date(2024, 2, 23)),
        ),
    ]
