# Generated by Django 4.2.8 on 2024-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_parametro_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='criado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
